image: Visual Studio 2017

environment:  
  DOCKER_USER:
    secure: WK7l3/NryEGz/PyM2ug61g==
  DOCKER_PASSWORD:
    secure: YVM7mNidCYiJdmoc7ficOTmVTpfgGGYkNPWVBicVTMM=

install:  
  - ps: docker version

build_script:  
  - ps: .\build.ps1

test_script:  
  - ps: .\test.ps1

deploy_script:  
  - ps: .\deploy.ps1
