image: Visual Studio 2017

environment:  
  DOCKER_USER:
    secure: WK7l3/NryEGz/PyM2ug61g==
  DOCKER_PASSWORD:
    secure: YVM7mNidCYiJdmoc7ficOTmVTpfgGGYkNPWVBicVTMM=

install:  
  - ps: docker version

build_script:  
  - ps: docker build -t moiamond/ffmpeg-base-windowsservercore .

test_script:  
  - ps: docker images

deploy_script:  
  - ps: .\deploy.ps1
